# Generated by Django 4.1 on 2022-08-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie',
            new_name='collection',
        ),
    ]
