# Generated by Django 4.1 on 2022-08-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_movie_collection_movie_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='collection',
        ),
        migrations.AddField(
            model_name='collection',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies.movie'),
        ),
    ]
