# Generated by Django 4.0.7 on 2022-08-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_remove_collection_movies_movie_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='id',
        ),
        migrations.AddField(
            model_name='movie',
            name='uuid',
            field=models.CharField(default=1, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='collection',
        ),
        migrations.AddField(
            model_name='movie',
            name='collection',
            field=models.ManyToManyField(related_name='movies', to='movies.collection'),
        ),
    ]
